version: "3"

services:
  db:
    image: postgis/postgis:14-3.1
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: froide
      POSTGRES_DB: froide
      POSTGRES_PASSWORD: froide
    ports:
      - "127.0.0.1:5432:5432"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  es-data:
    driver: local
  pg-data: {}
